apiVersion: batch/v1
kind: CronJob
metadata:
  name: notification-resetter-cronjob
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: notification-resetter
            # https://catalog.redhat.com/en/software/containers/ubi9/python-314/690b0a9fcfc8d02bfb0d341e
            image: registry.access.redhat.com/ubi9/python-314:9.8-1787079087@sha256:194df4e35e0e5467e1b57266f4d61f821e1b1f567135f074d23066d3604ae653
            env:
              - name: QUAY_ORG
                valueFrom:
                  secretKeyRef:
                    name: quaytoken
                    key: organization
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - '-c'
              - python /notification-resetter/reset_notifications.py --namespace $(QUAY_ORG)
            volumeMounts:
              - name: notification-resetter-volume
                mountPath: /notification-resetter
              - name: quaytoken
                mountPath: /secrets/quaytoken
                readOnly: true
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 150m
                memory: 128Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - "ALL"
              readOnlyRootFilesystem: true
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: notification-resetter-volume
              configMap:
                name: notification-resetter-configmap
            - name: quaytoken
              secret:
                secretName: quaytoken
