apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: image-c-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/redhat-appstudio/pull-request-builds:image-controller-{{revision}}"
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: gomod
  pipelineRef:
    name: docker-build
    bundle: quay.io/redhat-appstudio-tekton-catalog/pipeline-core-services-docker-build:latest
  workspaces:
    - name: registry-auth
      secret:
        secretName: redhat-appstudio-registry-pull-secret
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
