name: Codecov report on push to the "main" branch
on:
  push:
    branches: [ main ]
jobs:
  coverage:
    name: Upload code coverage report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
      - name: Run tests and collect coverage
        run: make test
      - name: Upload Codecov Report
        uses: codecov/codecov-action@v3
